### ISSUE TITLE
[troubleshooting] requesting reviews

### ISSUE THREAD

**Issue by MayaAndersonGonzalez** [libscie/handbook#7]
I would like to request a review of this [pull request](https://github.com/libscie/handbook/pull/6), but documentation says ["Pull request authors can't request reviews unless they are either a repository owner or collaborator with write access to the repository."](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) 
Did I create the pull request in the wrong place ?

**Comment by chartgerink** [comment]
Thanks @MayaAndersonGonzalez - this is not the wrong place at all. Apparently settings are more restrictive than I expected! I'll update this in the documentation.
